Workaround Uninstall bug: https://issues.redhat.com/browse/ACM-2258
Signed-off-by: nmanos <nmanos@redhat.com>

diff --git a/acm_functions b/acm_functions
--- a/acm_functions
+++ b/acm_functions
@@ -106,6 +106,7 @@ function remove_acm_managed_cluster() {
 
 function clean_acm_namespace_and_resources() {
 ### Uninstall ACM MultiClusterHub ###
+# Ref: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html/install/installing#uninstalling
   trap_to_debug_commands;
 
   # Should be run on the ACM MultiClusterHub cluster only
@@ -116,34 +117,98 @@ function clean_acm_namespace_and_resources() {
 
   PROMPT "Uninstalling previous ACM Hub instance from cluster ${cluster_name}"
 
-  local acm_uninstaller_url="https://raw.githubusercontent.com/open-cluster-management/deploy/master/multiclusterhub/uninstall.sh"
-  local acm_uninstaller_file="./acm_cleanup.sh"
+  # Should be deprecated - The open-cluster-management github script is not officially supported:
+  #
+  # local acm_uninstaller_url="https://raw.githubusercontent.com/open-cluster-management/deploy/master/multiclusterhub/uninstall.sh"
+  # local acm_uninstaller_file="./acm_cleanup.sh"
+  #
+  # TITLE "Uninstalling ACM with the uninstall.sh script from Github: \n
+  # ${acm_uninstaller_url}"
+  #
+  # download_file "${acm_uninstaller_url}" "${acm_uninstaller_file}"
+  # chmod +x "${acm_uninstaller_file}"
+  # sed -i 's/kubectl /oc /' "${acm_uninstaller_file}" 
+  #
+  # # TODO: Use script from https://github.com/open-cluster-management/acm-qe/wiki/Cluster-Life-Cycle-Component
+  # # https://raw.githubusercontent.com/open-cluster-management/deploy/master/hack/cleanup-managed-cluster.sh
+  # # https://github.com/open-cluster-management/endpoint-operator/raw/master/hack/hub-detach.sh
+  #
+  # export TARGET_NAMESPACE="${ACM_NAMESPACE}"
+  # ${acm_uninstaller_file} || :
+  #
+  # BUG "ACM uninstaller script does not delete all resources" \
+  # "Delete ACM resources directly" \
+  # "https://github.com/open-cluster-management/deploy/issues/218"
+  # # Workaround:
 
-  TITLE "Uninstalling ACM with the uninstall.sh script from Github: \n
-  ${acm_uninstaller_url}"
+  ${OC} delete managedcluster --all --timeout=3m || :
 
-  download_file "${acm_uninstaller_url}" "${acm_uninstaller_file}"
-  chmod +x "${acm_uninstaller_file}"
-  sed -i 's/kubectl /oc /' "${acm_uninstaller_file}" 
+  ${OC} delete DiscoveryConfig --all --all-namespaces --timeout=3m || :
+  ${OC} delete MultiClusterObservability --all --timeout=3m || :
+  ${OC} delete MultiClusterHub --all --timeout=3m || :
 
-  # TODO: Use script from https://github.com/open-cluster-management/acm-qe/wiki/Cluster-Life-Cycle-Component
-    # https://raw.githubusercontent.com/open-cluster-management/deploy/master/hack/cleanup-managed-cluster.sh
-    # https://github.com/open-cluster-management/endpoint-operator/raw/master/hack/hub-detach.sh
+  # Show ACM resources
+  ${OC} get MultiClusterHub -o yaml
+  ${OC} api-resources | grep -E "multicluster|open-cluster"
 
-  export TARGET_NAMESPACE="${ACM_NAMESPACE}"
-  ${acm_uninstaller_file} || :
-  
-  BUG "ACM uninstaller script does not delete all resources" \
-  "Delete ACM resources directly" \
-  "https://github.com/open-cluster-management/deploy/issues/218"
-  # Workaround:
+  # helm ls --namespace $ACM_NAMESPACE | cut -f 1 | tail -n +2 | xargs -n 1 helm delete --namespace $ACM_NAMESPACE
+  ${OC} delete apiservice \
+  v1beta2.webhook.certmanager.k8s.io \
+  v1.admission.cluster.open-cluster-management.io \
+  v1.admission.work.open-cluster-management.io --timeout=3m || :
+
+  ${OC} delete clusterimageset --all --timeout=3m || :
+
+  ${OC} delete clusterrole \
+  multiclusterengines.multicluster.openshift.io-v1-admin \
+  multiclusterengines.multicluster.openshift.io-v1-crdview \
+  multiclusterengines.multicluster.openshift.io-v1-edit \
+  multiclusterengines.multicluster.openshift.io-v1-view --timeout=3m || :
+
+  ${OC} delete configmap -n $ACM_NAMESPACE \
+  cert-manager-controller \
+  cert-manager-cainjector-leader-election \
+  cert-manager-cainjector-leader-election-core --timeout=3m || :
+
+  ${OC} delete consolelink acm-console-link --timeout=3m || :
+
+  ${OC} delete crd \
+  klusterletaddonconfigs.agent.open-cluster-management.io \
+  placementbindings.policy.open-cluster-management.io \
+  policies.policy.open-cluster-management.io \
+  userpreferences.console.open-cluster-management.io \
+  searchservices.search.acm.com \
+  discoveredclusters.discovery.open-cluster-management.io \
+  discoveryconfigs.discovery.open-cluster-management.io --timeout=3m || :
+
+  ${OC} delete mutatingwebhookconfiguration \
+  cert-manager-webhook cert-manager-webhook-v1alpha1 ocm-mutating-webhook \
+  managedclustermutators.admission.cluster.open-cluster-management.io \
+  multicluster-observability-operator --timeout=3m || :
+
+  ${OC} delete oauthclient multicloudingress --timeout=3m || :
+
+  ${OC} delete rolebinding -n kube-system \
+  cert-manager-webhook-webhook-authentication-reader --timeout=3m || :
+
+  ${OC} delete scc kui-proxy-scc --timeout=3m || :
+
+  ${OC} delete validatingwebhookconfiguration \
+  cert-manager-webhook \
+  cert-manager-webhook-v1alpha1 \
+  channels.apps.open.cluster.management.webhook.validator \
+  application-webhook-validator \
+  multiclusterhub-operator-validating-webhook \
+  ocm-validating-webhook \
+  multicluster-observability-operator \
+  multiclusterengines.multicluster.openshift.io --timeout=3m || :
+
 
   TITLE "Delete global CRDs, Managed Clusters, and Validation Webhooks of ACM in cluster ${cluster_name}"
 
   delete_crds_by_name "open-cluster-management" || :
   delete_crds_by_name "multicluster" || :
 
-  ${OC} delete managedcluster --all --timeout=30s || :
   ${OC} delete validatingwebhookconfiguration --all --timeout=30s || :
   ${OC} delete manifestwork --all --timeout=30s || :
 
@@ -160,6 +225,8 @@ function clean_acm_namespace_and_resources() {
   ${OC} delete service --all -n "${ACM_NAMESPACE}" --timeout=30s || :
 
   force_delete_namespace "${MCE_NAMESPACE}" 1m || :
+  force_delete_namespace "${ACM_HUB_NS}" 1m || :
+  force_delete_namespace "${ACM_GS_NS}" 1m || :
   force_delete_namespace "${ACM_NAMESPACE}" 1m || :
 
 }
@@ -184,7 +251,7 @@ function check_if_mce_is_required() {
     check_version_greater_or_equal "$acm_current_version" "2.5" || return 1
   fi
 
-  echo -e "\n# MCE $MCE_VER_TAG should be installed perior to ACM $ACM_VER_TAG"
+  echo -e "\n# MCE $MCE_VER_TAG should be installed prior to ACM $ACM_VER_TAG"
 
 }
 
