Improve watch_and_retry to accept timeout or number of retries
Workaround for bugs:
https://github.com/submariner-io/submariner/issues/576
https://github.com/submariner-io/submariner-operator/issues/390

diff --git a/helper_functions b/helper_functions
--- a/helper_functions
+++ b/helper_functions
@@ -17,6 +17,8 @@ export CONDA_ENV_NAME="conda-test"
 
 shopt -s nocasematch # Case-insensitive match for string evaluations
 
+set -o allexport # To export each function when it is declared, to be used on external bash processes
+
 # Functions #
 
 function print_cmd_location() {
@@ -65,13 +67,13 @@ trap_commands
 # to Highlight matches and Return exit code (5 if no match found):
 function highlight()
 {
+  # trap_commands
   pattern="$1"
-  exit_code=0
   shift
-  sed '/'"$pattern"'/,${s//'$YELLOW'&'$NO_COLOR'/g;b};$q5' "$@" &> /dev/null || exit_code=$?
+  sed -r '/'"$pattern"'/,${s//'$YELLOW'&'$NO_COLOR'/g;b};$q5' "$@" || exit_code=$?
   if [[ $exit_code = 1 ]] ; then
     exit_code=0
-    sed -E '/'"$pattern"'/,${s//'$YELLOW'&'$NO_COLOR'/g;b};$q5' "$@" || exit_code=$?
+    sed -e '/'"$pattern"'/,${s//'$YELLOW'&'$NO_COLOR'/g;b};$q5' "$@" || exit_code=$?
   fi
   return $exit_code
 }
@@ -80,34 +82,38 @@ function highlight()
 
 # function to watch for expected regex of command output, with retry attempts
 function watch_and_retry() {
-  #trap_commands
+  # trap_commands
 
   # Command to watch. Variables should be escaped, e.g. \$var
   CMD="$1"
-  # Optional: Number of retry attempts (default=10)
+  # Optional: Number of retry attempts (default is 10)
   RETRY=${2:-10}
   # Optional: Pattern to search, otherwise expect $CMD exit 0
   REGEX="$3"
+  # Max timeout for the whole watch process (default is 10 minutes)
+  TIMEOUT=10m
 
-  # If regex specified, will wait for regex to be found in CMD output
-  # [[ -z ${REGEX} ]] || CMD="$CMD"' | grep -m 1 "'"$REGEX"'"'
-  [[ -z ${REGEX} ]] || CMD="$CMD"' |& highlight "'"$REGEX"'"'
+  # If REGEX was specified - will wait for REGEX to be found in CMD output
+  [[ -z "$REGEX" ]] || CMD="$CMD |& highlight '$REGEX'"
 
   echo -e "# Watching output of command: $(eval echo \"$CMD\") \n\
   # Search pattern (or exit code):/$REGEX/ \n\
-  # Retry attempts: $RETRY"
+  # Retry attempts / timeout: $RETRY"
 
+  # Set timeout for the whole process, if RETRY is number of seconds/minutes (e.g. 20s or 3m)
+  [[ ! "$RETRY" =~ [0-9]+[sm] ]] || TIMEOUT=$RETRY && RETRY=-1
   COUNT=0;
-  until eval "$CMD" || [[ $COUNT -eq $RETRY ]] ; do
-    echo -e "$(( COUNT++ ))... \c"
-    sleep 1 # A second interval
-    # [[ $COUNT -eq $RETRY ]] && break
-  done
-  if [[ $COUNT -eq $RETRY ]]; then
-    echo "# Limit of $RETRY attempts has exceeded."
-    return 1
-  fi
-  return 0
+  timeout $TIMEOUT bash <<EOF
+    until eval "$CMD" || [[ $COUNT -eq $RETRY ]] ; do
+      echo -e "$(( COUNT++ ))... \c"
+      sleep 1 # A second interval
+    done
+    if [[ $COUNT -eq $RETRY ]]; then
+      echo "# Limit of $RETRY attempts/timeout has exceeded."
+      exit 1
+    fi
+    exit 0
+EOF
 }
 
 # ------------------------------------------
