Add new helper function FAILURE() to fail just current test
Increase E2E Ginkgo tests timeout to 120m

Fix Ginkgo report file path

Signed-off-by: Noam Manos <nmanos@redhat.com>

diff --git a/helper_functions b/helper_functions
--- a/helper_functions
+++ b/helper_functions
@@ -182,9 +182,18 @@ function PROMPT() {
 
 # ------------------------------------------
 
-# Function to print message about a potential bug/workaround, and an optional bug link
+# Function to print FAILURE message and return 1 for the current test
+function FAILURE() {
+  local failure_msg="${1}"
+  echo -e "\n${RED}*** Failure occurred *** \n $failure_msg ${NO_COLOR}" >&2
+  return 1
+}
+
+# ------------------------------------------
+
+# Function to print FATAL message and exit the whole test suite
 function FATAL() {
-  failure_msg="${1}"
+  local failure_msg="${1}"
   echo -e "\n${RED}*** Fatal error occurred *** \n $failure_msg ${NO_COLOR}" >&2
   # kill -s TERM $$
   # kill -s TERM $BASHPID
@@ -239,7 +248,6 @@ function record_junit() {
   +++ into xml output file \"${output_dir}/${output_file}\""
 
   juLog -output="$output_dir" -file="$output_file" -index -class="$junit_suite" -name="$test_name" "$func_and_args"
-  # juLog -output="$output_dir" -file="$output_file" -class="$junit_suite" -name="$test_name" "$func_and_args"
 }
 
 # ------------------------------------------
