Workaround for bug: https://github.com/submariner-io/lighthouse/issues/212
Add watch_pod_logs() function for Submariner pods tests
Add print_pod_logs_in_namespace() for collect_submariner_info()

diff --git a/helper_functions b/helper_functions
--- a/helper_functions
+++ b/helper_functions
@@ -55,7 +55,7 @@ function highlight()
   # 3 = Match not found
   # 4 = Empty string or file
 
-  #local TEMP_FILE="`mktemp`_highlight"
+  local TEMP_FILE="`mktemp`_highlight"
   # Save all output to temp file
   #grep -E "$pattern|$" "$@" > $TEMP_FILE
   grep -E "$pattern|$" ${file_input:+"$file_input"} > $TEMP_FILE
@@ -649,6 +649,44 @@ function install_nginx_service() {
   ${OC} rollout status deployment ${ngnix_name} ${target_namespace:+-n $target_namespace}
   ${OC} describe pod ${ngnix_name} ${target_namespace:+-n $target_namespace}
 
+}
+
+# ------------------------------------------
+
+# Function to tail pod logs for N times, after each interval
+function watch_pod_logs() {
+  trap_commands;
+
+  local pod_to_watch="$1"
+  local namespace="$2"
+  local regex="$3"
+
+  # Optional params:
+  local retries=${4:-5}
+  local interval=${5:-20s} # time between each retry attempt
+  local TEMP_FILE="`mktemp`_pod_log"
+
+  echo -e "# Tailing logs of Pod [$globalnet_pod] in Namespace [$namespace]: \n"
+
+  cmd="${OC} logs --timestamps --since=$interval $pod_to_watch -n $namespace \
+  > $TEMP_FILE && sleep $interval && cat $TEMP_FILE"
+
+  watch_and_retry "$cmd" "$retries" "$regex"
+}
+
+# ------------------------------------------
+
+function print_pod_logs_in_namespace() {
+  local namespace="$1"
+  local pods_label="${2:+ -l $2}"
+  echo -e "\n##################### Pods descriptions and logs ${2:+ by label "$2"} in Namespace: ${namespace} #####################\n"
+
+  for pod in $(${OC} get pods $pods_label -n $namespace -o jsonpath='{.items[*].metadata.name}'); do
+      echo -e "\n### Pod $pod in Namespace $namespace ###\n"
+      ${OC} -n $namespace describe pod $pod || :
+      ${OC} -n $namespace get pod $pod -o yaml || :
+      ${OC} -n $namespace logs $pod || :
+  done
 }
 
 # ------------------------------------------
