Use delete_crds_by_name() and force_delete_namespace() for ACM
Signed-off-by: nmanos <nmanos@redhat.com>

diff --git a/helper_functions b/helper_functions
--- a/helper_functions
+++ b/helper_functions
@@ -831,54 +831,55 @@ function ocp_login() {
 
 # ------------------------------------------
 
-# Function to delete selected namespace and CRDs on the current KUBECONFIG cluster
-function delete_namespace_and_crds() {
+# Function to delete all CRDs wich includes the input text on the current cluster
+function delete_crds_by_name() {
   trap_to_debug_commands;
-  # Input $1 : Namespace to delete
-  # Input $2 (Optional) : All CRDs to delete, by searching for *crd_name*
-  local ns_name=$1
-  local crd_name=$2
+
+  # Input $1 : All CRDs to delete, by searching for *crd_name*
+  local crd_name=$1
 
   local delete_crds=FALSE
 
-  if [[ -n $crd_name ]] ; then
-    echo "# Searching for existing CRDs of previous ${crd_name} installation on the cluster:"
-    ${OC} get crds |& highlight "${crd_name}" && delete_crds=TRUE || :
+  echo "# Searching for existing CRDs of previous ${crd_name} installation on the cluster:"
+  ${OC} get crds |& highlight "${crd_name}" && delete_crds=TRUE || :
 
-    # If there are existing CRDs on the cluster - remove them all:
-    # if [[ $? = 0 ]]; then
-    if [[ "$delete_crds" = TRUE ]]; then
-      echo "# Deleting ${crd_name} CRDs in the cluster"
-      crd_list=$(${OC} get crds -o name | grep -Po "\/\K.*${crd_name}.*")
-      # Ignoring hanged CRDs on delete, due to K8s bug: https://github.com/kubernetes/kubernetes/issues/60538
-      ${OC} delete --timeout=10s crds $crd_list --ignore-not-found || : # || : to ignore none-zero exit code
-    fi
-  fi
-
-    echo "# Searching for existing resources (and OLMs) in namespace ${ns_name} :"
-    # ${OC} get all,olm --all-namespaces | grep --color "${crd_name}" || delete_namespace=FALSE
-    ${OC} get all,olm -n ${ns_name} |& highlight "No resources found" || :
-
-  # Removing whole namespace (and it's resources):
-  if [[ ${ns_name} = "default" ]] ; then
-    echo "# Skipping namespace deletion, since it's the \"default\" namespace."
-    return
+  # If there are existing CRDs on the cluster - remove them all:
+  # if [[ $? = 0 ]]; then
+  if [[ "$delete_crds" = TRUE ]]; then
+    echo "# Deleting ${crd_name} CRDs in the cluster"
+    crd_list=$(${OC} get crds -o name | grep -Po "\/\K.*${crd_name}.*")
+    # Ignoring hanged CRDs on delete, due to K8s bug: https://github.com/kubernetes/kubernetes/issues/60538
+    ${OC} delete --timeout=10s crds $crd_list --ignore-not-found || : # || : to ignore none-zero exit code
   else
-    echo "# Deleting whole namespace ${ns_name} from the cluster"
-    force_delete_namespace "${ns_name}"
+    echo "# No CRD with '${crd_name}' was found in the current cluster"
   fi
+
 }
 
 
 # ------------------------------------------
 
-# Function to force delete namespace
+# Function to force delete a namespace
 function force_delete_namespace() {
   trap_to_debug_commands;
   # Input $1 : Namespace to delete
-  ns_name=$1
+  local ns_name="$1"
 
-  ${OC} delete --timeout=30s namespace ${ns_name} --ignore-not-found || force_ns_delete=TRUE
+  # Input $2 (Optional) : Timeout to wait before forcing namespace deletion
+  local delete_timeout="${2:-30s}"
+
+  if [[ ${ns_name} = "default" ]] ; then
+    echo "# Skipping namespace deletion, since it's the \"default\" namespace."
+    return
+  fi
+
+  echo "# Show all resources (and OLMs) in namespace ${ns_name} to be deleted:"
+  # ${OC} get all,olm --all-namespaces | grep --color "${crd_name}" || delete_namespace=FALSE
+  ${OC} get all,olm -n ${ns_name} |& highlight "No resources found" || :
+
+  TITLE "Deleting whole namespace ${ns_name} from the cluster"
+
+  ${OC} delete --timeout=$delete_timeout namespace ${ns_name} --ignore-not-found || force_ns_delete=TRUE
 
   if [[ "$force_ns_delete" = TRUE && $(${OC} get namespace ${ns_name}) ]]; then
     echo "# Warning: Force delete of namespace via API"
@@ -948,7 +949,6 @@ function install_nginx_service() {
 
   if [[ -n "$target_namespace" ]] ; then
     echo "# Create Namespace for Nginx: $target_namespace"
-    # delete_namespace_and_crds "${target_namespace}"
     create_namespace "${target_namespace}"
   fi
 
