Add force delete to namespaces from API

diff --git a/helper_functions b/helper_functions
--- a/helper_functions
+++ b/helper_functions
@@ -2,7 +2,19 @@
 
 ### General Helpers Function ###
 
+# Constants #
+
+export RED='\x1b[0;31m'
+export GREEN='\x1b[38;5;22m'
+export CYAN='\x1b[36m'
+export YELLOW='\x1b[33m' #'\x1b[32m'
+export NO_COLOR='\x1b[0m'
+export HAT="${RED}🎩︎${NO_COLOR}"
+
 shopt -s nocasematch # Case-insensitive match for string evaluations
+
+
+# Functions #
 
 function print_cmd_location() {
   new_location="[$0] [${PWD##*/}]" && \
@@ -10,8 +22,10 @@ function print_cmd_location() {
     export current_location="$new_location"
     echo -e "\n${CYAN}$current_location${NO_COLOR}\n"
   fi
-  echo -e "${CYAN}${1}${NO_COLOR}" 2>/dev/null
-  #echo -e "${CYAN}${1}${NO_COLOR}"
+  # echo -e "${CYAN}${1}${NO_COLOR}"
+  cmd="$(eval echo -e \"${1}\" 2>/dev/null)"
+  echo -e "${CYAN}${cmd}${NO_COLOR}"
+
 }
 
 # ------------------------------------------
@@ -372,43 +386,48 @@ function delete_aws_dns_records() {
 function delete_namespace_and_crds() {
   trap_commands;
   # Input $1 : Namespace to delete
-  # Input $2 : All CRDs to delete, by searching for *crd_name*
+  # Input $2 - Optional : All CRDs to delete, by searching for *crd_name*
   ns_name=$1
   crd_name=$2
   delete_namespace=FALSE
   delete_crds=FALSE
+  force_ns_delete=FALSE
 
-  echo "# Search for existing CRDs of previous ${crd_name} installation on the Cluster:"
-  ${OC} get crds |& highlight "${crd_name}" && delete_crds=TRUE || :
+  if [[ -n $crd_name ]] ; then
+    echo "# Searching for existing CRDs of previous ${crd_name} installation on the cluster:"
+    ${OC} get crds |& highlight "${crd_name}" && delete_crds=TRUE || :
 
-  # If there are existing CRDs on the Cluster - remove them all:
-  # if [[ $? = 0 ]]; then
-  if [[ "$delete_crds" = TRUE ]]; then
-    echo "# Deleting ${ns_name} CRDs in the Cluster"
-    crd_list=$(${OC} get crds -o name | grep -Po "\/\K.*${crd_name}.*")
-    # Ignoring hanged CRDs on delete, due to K8s bug: https://github.com/kubernetes/kubernetes/issues/60538
-    ${OC} delete --timeout=10s crds $crd_list || : # || : to ignore none-zero exit code
-        # customresourcedefinition.apiextensions.k8s.io "clusters.submariner.io" deleted
-        # customresourcedefinition.apiextensions.k8s.io "endpoints.submariner.io" deleted
-        # customresourcedefinition.apiextensions.k8s.io "submariners.submariner.io" deleted
+    # If there are existing CRDs on the cluster - remove them all:
+    # if [[ $? = 0 ]]; then
+    if [[ "$delete_crds" = TRUE ]]; then
+      echo "# Deleting ${ns_name} CRDs in the cluster"
+      crd_list=$(${OC} get crds -o name | grep -Po "\/\K.*${crd_name}.*")
+      # Ignoring hanged CRDs on delete, due to K8s bug: https://github.com/kubernetes/kubernetes/issues/60538
+      ${OC} delete --timeout=10s crds $crd_list --ignore-not-found || : # || : to ignore none-zero exit code
+          # customresourcedefinition.apiextensions.k8s.io "clusters.submariner.io" deleted
+          # customresourcedefinition.apiextensions.k8s.io "endpoints.submariner.io" deleted
+          # customresourcedefinition.apiextensions.k8s.io "submariners.submariner.io" deleted
+    fi
   fi
 
-  echo "# Search for existing resources (and OLMs) in namespace ${ns_name} :"
+  echo "# Searching for existing resources (and OLMs) in namespace ${ns_name} :"
   # ${OC} get all,olm --all-namespaces | grep --color "${crd_name}" || delete_namespace=FALSE
-  ${OC} get all,olm -n ${ns_name} |& highlight "No resources found" || delete_namespace=TRUE || :
+  ${OC} get all,olm -n ${ns_name} |& highlight "No resources found" || :
 
-  # If there are existing resources on the Cluster - remove them all:
-  if [[ "$delete_namespace" = TRUE ]]; then
-    echo "# Deleting whole namespace ${ns_name} from the Cluster"
-    ${OC} delete --timeout=10s namespace ${ns_name} || : # || : to ignore none-zero exit code
+  # If there is existing namespace on the cluster - remove it:
+  # if [[ "$delete_namespace" = TRUE ]]; then
+    echo "# Deleting whole namespace ${ns_name} from the cluster"
+    ${OC} delete --timeout=10s namespace ${ns_name} --ignore-not-found || force_ns_delete=TRUE
 
-      # ${OC} delete Submariner submariner -n submariner-operator
-        # submariner.submariner.io "submariner" deleted
-
-      # ${OC} delete olm,services,rs,rc,subscriptions,deployments,jobs,pods --all -n openshift-submariner
-
-      # ${OC} delete olm,sa,services,rs,rc,subscriptions,deployments,jobs,pods --all -n submariner-operator
-  fi
+    if [[ "$force_ns_delete" = TRUE && $(${OC} get namespace ${ns_name}) ]]; then
+      echo "# Warning: using force delete of namespace"
+      ${OC} proxy &
+      ${OC} get namespace ${ns_name} -o json | jq '.spec = {"finalizers":[]}' > temp.json
+      curl -k -H "Content-Type: application/json" -X PUT --data-binary @temp.json 127.0.0.1:8001/api/v1/namespaces/${ns_name}/finalize
+      kill -9 %% || :
+      ${OC} delete --timeout=30s namespace ${ns_name} --ignore-not-found
+    fi
+  # fi
 
 }
 
