Add common function export_all_env_variables()
Signed-off-by: nmanos <nmanos@redhat.com>

diff --git a/test_functions b/test_functions
--- a/test_functions
+++ b/test_functions
@@ -681,58 +681,173 @@ function create_osp_cluster() {
 
 # ------------------------------------------
 
-function export_active_clusters_kubeconfig() {
-### Helper function to unset inactive clusters kubeconfig ###
-  trap_to_debug_commands;
+function export_all_env_variables() {
+### Helper function to export all environment and test variables ###
+  PROMPT "Exporting environment and test variables"
 
-  # TODO: Need to re-factor so any cluster A/B/C have same function to export its name, dir, etc.
+  ### Set script in debug/verbose mode, if used CLI option: --debug / -d ###
+  if [[ "$SCRIPT_DEBUG_MODE" =~ ^(yes|y)$ ]]; then
 
-  local ocp_yaml_platform
-  local ocp_yaml_base_dns
+    trap_to_debug_commands;
 
-  TITLE "Exporting all active clusters kubeconfig (and unset inactive kubeconfigs)"
+    # Extra verbosity for oc commands:
+    # https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-output-verbosity-and-debugging
+    # export VERBOSE_FLAG="--v=2"
+    # export OC="$OC $VERBOSE_FLAG"
 
-  # Setting HUB (Cluster A) config ($WORKDIR and $CLUSTER_A_NAME were set in subm_variables file)
+    # Debug flag for ocpup and aws commands
+    export DEBUG_FLAG="--debug"
 
-  # Get cluster platform and base domain from OCP installer yaml, and append it to the cluster name
-  ocp_yaml_platform="$(grep -Poz 'platform:\s*\K\w+' "${CLUSTER_A_YAML}" | awk -F'\0' '{print $1; exit}' || :)"
-  # ocp_yaml_base_dns="$(grep -Poz 'baseDomain:\s*\K\w+' ${CLUSTER_A_NAME} | awk -F'\0' '{print $1; exit}}' || :)"
-  export CLUSTER_A_NAME="${CLUSTER_A_NAME}${ocp_yaml_base_dns:+-$ocp_yaml_base_dns}${ocp_yaml_platform:+-$ocp_yaml_platform}"
-
-  echo -e "\n# Exporting \$KUBECONF_HUB for $CLUSTER_A_NAME (Cluster A is also the ACM Hub)"
-  export CLUSTER_A_DIR=${WORKDIR}/${CLUSTER_A_NAME}
-  export KUBECONF_HUB=${CLUSTER_A_DIR}/auth/kubeconfig
-
-  # Setting Cluster B config ($OCPUP_DIR and $CLUSTER_B_YAML were set in subm_variables file)
-  if [[ -s "$CLUSTER_B_YAML" ]] ; then
-    echo -e "\n# Exporting \$KUBECONF_CLUSTER_B for $CLUSTER_B_NAME"
-    CLUSTER_B_DIR=${OCPUP_DIR}/.config/$(awk '/clusterName:/ {print $NF}' "${CLUSTER_B_YAML}")
-    export CLUSTER_B_DIR
-    KUBECONF_CLUSTER_B=${CLUSTER_B_DIR}/auth/kubeconfig
-    export KUBECONF_CLUSTER_B
-    export KUBECONF_MANAGED="${KUBECONF_CLUSTER_B}"
   else
-    echo -e "\n# Cluster B was not installed - Unset \$KUBECONF_CLUSTER_B"
-    unset KUBECONF_CLUSTER_B
-    unset CLUSTER_B_NAME
+    # Clear trap_to_debug_commands function
+    trap_to_debug_commands() { :; }
   fi
 
+  # cd "${SCRIPT_DIR}"
+
+  set_missing_cli_variables
+
+  # Setting HUB (Cluster A) config ($WORKDIR and $CLUSTER_A_NAME were set in subm_variables file)
+  export_cluster_config_variables "${CLUSTER_A_NAME}" "${CLUSTER_A_YAML}" "A"
+
+  # Setting Cluster B config ($OCPUP_DIR and $CLUSTER_B_YAML were set in subm_variables file)
+  export_cluster_config_variables "${CLUSTER_B_NAME}" "${CLUSTER_B_YAML}" "B"
+
   # Setting Cluster C config ($WORKDIR and $CLUSTER_C_NAME were set in subm_variables file)
-  if [[ -s "$CLUSTER_C_YAML" ]] ; then
-    echo -e "\n# Exporting \$KUBECONF_CLUSTER_C for $CLUSTER_C_NAME"
+  export_cluster_config_variables "${CLUSTER_C_NAME}" "${CLUSTER_C_YAML}" "C"
 
-    # Get cluster platform and base domain from OCP installer yaml, and append it to the cluster name
-    ocp_yaml_platform="$(grep -Poz 'platform:\s*\K\w+' "${CLUSTER_C_YAML}" | awk -F'\0' '{print $1; exit}' || :)"
-    # ocp_yaml_base_dns="$(grep -Poz 'baseDomain:\s*\K\w+' ${CLUSTER_C_YAML} | awk -F'\0' '{print $1; exit}}' || :)"
-    export CLUSTER_C_NAME="${CLUSTER_C_NAME}${ocp_yaml_base_dns:+-$ocp_yaml_base_dns}${ocp_yaml_platform:+-$ocp_yaml_platform}"
+  # Set $SUBM_VER_TAG and $ACM_VER_TAG variables with the correct version (vX.Y.Z), branch name, or tag
+  set_versions_variables
 
-    export CLUSTER_C_DIR=${WORKDIR}/${CLUSTER_C_NAME}
-    export KUBECONF_CLUSTER_C=${CLUSTER_C_DIR}/auth/kubeconfig
-    export KUBECONF_MANAGED="${KUBECONF_CLUSTER_C}"
+}
+
+# ------------------------------------------
+
+function set_missing_cli_variables() {
+### Helper function to set missing cli/user variable ###
+  trap_to_debug_commands;
+
+  TITLE "Set CLI/User inputs if missing (Default is 'NO' for any unset variable)"
+
+  export GET_OCP_INSTALLER=${GET_OCP_INSTALLER:-NO}
+  # export OCP_VERSION=${OCP_VERSION}
+  export GET_OCPUP_TOOL=${GET_OCPUP_TOOL:-NO}
+  # export BUILD_OPERATOR=${BUILD_OPERATOR:-NO} # [DEPRECATED]
+  export BUILD_GO_TESTS=${BUILD_GO_TESTS:-NO}
+  export INSTALL_ACM=${INSTALL_ACM:-NO}
+  export INSTALL_MCE=${INSTALL_MCE:-NO}
+  export INSTALL_SUBMARINER=${INSTALL_SUBMARINER:-NO}
+  export INSTALL_WITH_SUBCTL=${INSTALL_WITH_SUBCTL:-NO}
+  export REGISTRY_IMAGES=${REGISTRY_IMAGES:-NO}
+  export DESTROY_CLUSTER_A=${DESTROY_CLUSTER_A:-NO}
+  export CREATE_CLUSTER_A=${CREATE_CLUSTER_A:-NO}
+  export RESET_CLUSTER_A=${RESET_CLUSTER_A:-NO}
+  export CLEAN_CLUSTER_A=${CLEAN_CLUSTER_A:-NO}
+  export DESTROY_CLUSTER_B=${DESTROY_CLUSTER_B:-NO}
+  export CREATE_CLUSTER_B=${CREATE_CLUSTER_B:-NO}
+  export RESET_CLUSTER_B=${RESET_CLUSTER_B:-NO}
+  export CLEAN_CLUSTER_B=${CLEAN_CLUSTER_B:-NO}
+  export DESTROY_CLUSTER_C=${DESTROY_CLUSTER_C:-NO}
+  export CREATE_CLUSTER_C=${CREATE_CLUSTER_C:-NO}
+  export RESET_CLUSTER_C=${RESET_CLUSTER_C:-NO}
+  export CLEAN_CLUSTER_C=${CLEAN_CLUSTER_C:-NO}
+  export JOIN_CLUSTER_A=${JOIN_CLUSTER_A:-NO}
+  export JOIN_CLUSTER_B=${JOIN_CLUSTER_B:-NO}
+  export JOIN_CLUSTER_C=${JOIN_CLUSTER_C:-NO}
+  export GLOBALNET=${GLOBALNET:-NO}
+  # export SUBM_CABLE_DRIVER=${SUBM_CABLE_DRIVER:-LIBRESWAN} [DEPRECATED]
+  export CONFIG_GOLANG=${CONFIG_GOLANG:-NO}
+  export CONFIG_AWS_CLI=${CONFIG_AWS_CLI:-NO}
+  export SKIP_OCP_SETUP=${SKIP_OCP_SETUP:-NO}
+  export SKIP_TESTS=${SKIP_TESTS:-NO}
+  export PRINT_LOGS=${PRINT_LOGS:-NO}
+  export CREATE_JUNIT_XML=${CREATE_JUNIT_XML:-NO}
+  export UPLOAD_TO_POLARION=${UPLOAD_TO_POLARION:-NO}
+  export SCRIPT_DEBUG_MODE=${SCRIPT_DEBUG_MODE:-NO}
+
+}
+
+# ------------------------------------------
+
+function export_cluster_config_variables() {
+### Helper function to set/unset cluster name and install directory (based on defaults from subm_variables file)
+
+  local cluster_name="$1"
+  local cluster_install_yaml="$2"
+  local cluster_index="$3" # A / B / C
+
+  TITLE "Exporting Cluster ${cluster_index} variables and kubeconfig (or unset if missing install yaml)"
+
+  if [[ -z "${cluster_name}" ]] ||
+     [[ -z "${cluster_install_yaml}" ]] ||
+     [[ -z "${cluster_index}" ]] ; then
+       FATAL "Required parameters for cluster installation are missing:
+       Cluster Name: ${cluster_name}
+       Cluster Installer YAML: ${cluster_install_yaml}
+       Cluster Index (A/B/C): ${cluster_index}
+       "
+  fi
+
+  local cluster_install_platform
+  local cluster_install_dir
+
+  if [[ -s "$cluster_install_yaml" ]] ; then
+    # Get cluster platform type from OCP installer yaml 
+    cluster_install_platform="$(print_ocp_install_platform "${cluster_install_yaml}")"
+    
+    # Append platform type to the cluster name
+    cluster_name+="-${cluster_install_platform}"
+
+    echo -e "\n# Exporting \$KUBECONF_CLUSTER_${cluster_index} for $cluster_name"
+
+    if [[ "$cluster_install_platform" = openstack ]] ; then
+      # TODO: This is just for Openstack (OCP install directory is defined by OCPUP yaml)
+      cluster_install_dir="${OCPUP_DIR}/.config/$(awk '/clusterName:/ {print $NF}' "${cluster_install_yaml}")"
+    else
+      cluster_install_dir="${WORKDIR}/${cluster_name}"
+    fi
+
+    trap_to_debug_commands;
+
+    export "CLUSTER_${cluster_index}_NAME=${cluster_name}"
+    export "CLUSTER_${cluster_index}_DIR=${cluster_install_dir}"
+    export "KUBECONF_CLUSTER_${cluster_index}=${cluster_install_dir}/auth/kubeconfig"
+    # export "KUBECONF_MANAGED=${cluster_install_dir}/auth/kubeconfig"
+  
   else
-    echo -e "\n# Cluster C was not installed - Unset \$KUBECONF_CLUSTER_C"
-    unset KUBECONF_CLUSTER_C
-    unset CLUSTER_C_NAME
+    echo -e "\n# Cluster $cluster_index installer yaml was not given - Unset \$KUBECONF_CLUSTER_${cluster_index}"
+    unset "KUBECONF_CLUSTER_${cluster_index}"
+    unset "CLUSTER_${cluster_index}_NAME"
+  fi
+
+}
+
+# ------------------------------------------
+
+function print_ocp_install_platform() {
+  # Print the platform type found in the OCP install yaml 
+  trap '' DEBUG # DONT trap_to_debug_commands
+
+  local ocp_install_yaml="$1"
+
+  grep -Poz 'platform:\s*(name:\s*)?\K\w+' "$ocp_install_yaml" | awk -F'\0' '{print $1; exit}' 2>/dev/null || :
+
+}
+
+# ------------------------------------------
+
+function check_if_cluster_is_running() {
+  # Check if cluster is already running (return exit code 1 if it's not) 
+  trap_to_debug_commands;
+
+  local kubeconfig_file="$1"
+
+  if ${OC} status --kubeconfig "${kubeconfig_file}" ; then
+    echo -e "\n# '$kubeconfig_file' default cluster is running"
+    return 0
+  else
+    echo -e "\n# '$kubeconfig_file' default cluster is not running (or not installed yet)"
+    return 1
   fi
 
 }
